### ISSUE TITLE
Silly author-test dependencies advertised as "runtime recommends"

### ISSUE THREAD

**Issue by kentfredric** [rurban/Filter#14]
https://github.com/rurban/Filter/blob/e5360f4b14f62f14e9eedd35b30d84b49b99b12d/Makefile.PL#L69-L83

https://metacpan.org/source/RURBAN/Filter-1.60/META.json#L33-46

Given that these dependencies aren't used for anything other than tests, and *authortests* at that, making them runtime recommendations is completely terrible.

In general, its preferred that authortests aren't even shipped in a way that subject end-users to their sillyness, but declaring the dependencies properly is better than nothing.

**Comment by rurban** [comment]
Would be the preferred meta tag for these then? TEST_REQUIRES? It simplified smoking for me, but I see that cpan users don't need them.

**Comment by kentfredric** [comment]
Ideally, for META_MERGE you want to use the v2 spec, and then use `test => { recommends => { } }`.

That is if you're insisting on them being dependencies at all.

**Comment by rurban** [comment]
Fine. Adding them as test recommends dependencies would make smoking much easier.

**Comment by rurban** [comment]
Done in master, will be in 1.61 soon
