### ISSUE TITLE
failed to upgrade because of INSTALLDIRS => 'perl'

### ISSUE THREAD

**Issue by powerman** [rurban/Filter#2]
What's the point of forcing INSTALLDIRS to 'perl' in Makefile.PL?

In Gentoo Linux package manager installs older (1.490) Filter to /usr/lib/perl/vendor_perl/ because some other packages depends on it. This result in failed attempt to update it using `cpanm R/RU/RURBAN/Filter-1.54.tar.gz` because Filter ignores cpanm configuration (install to /usr/local/lib/perl5/) and instead installs to /usr/lib/perl5/. Thus older version from vendor_perl/ is still used instead of newer just installed version.

**Comment by rurban** [comment]
That sounds certainly like a bug with this @INC order. Thanks

**Comment by powerman** [comment]
No, it's not. in `@INC` /usr/lib/perl/ (where you install) is always have less priority than all other local directories (site, vendor, /usr/local/lib/perl/, etc.) - otherwise it won't be possible to update any core module.

Actually, there was one more module with similar issue, check this: https://rt.cpan.org/Ticket/Display.html?id=103238

**Comment by powerman** [comment]
```
# perl -E 'say for @INC'
/etc/perl
/usr/local/lib64/perl5/5.20.2/x86_64-linux
/usr/local/lib64/perl5/5.20.2
/usr/lib64/perl5/vendor_perl/5.20.2/x86_64-linux
/usr/lib64/perl5/vendor_perl/5.20.2
/usr/local/lib64/perl5
/usr/lib64/perl5/vendor_perl
/usr/lib64/perl5/5.20.2/x86_64-linux
/usr/lib64/perl5/5.20.2
.
```

**Comment by rurban** [comment]
Yes, that's what I meant. @INC order changed with 5.12 and I need to fix it in Makefile.PL.

**Comment by rurban** [comment]
Should be fixed now. Sorry for being so late.
If not please reopen
